CREATE TABLE tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dashboard_id UUID NOT NULL REFERENCES dashboards(id) ON DELETE CASCADE,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  component TEXT,
  scope TEXT,
  acceptance_criteria TEXT,
  created_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  assigned_to_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  last_modified_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL,
  modified_at TIMESTAMPTZ NOT NULL,
  original_estimated_minutes INTEGER,
  priority VARCHAR(50),
  severity_id BIGINT REFERENCES severities(id) ON DELETE RESTRICT,
  state_id BIGINT NOT NULL REFERENCES states(id) ON DELETE RESTRICT,
  comments_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT tickets_original_estimated_minutes_check CHECK (
    original_estimated_minutes IS NULL OR original_estimated_minutes >= 0
  )
);

CREATE INDEX tickets_dashboard_id_idx ON tickets(dashboard_id);
CREATE INDEX tickets_created_by_user_id_idx ON tickets(created_by_user_id);
CREATE INDEX tickets_assigned_to_user_id_idx ON tickets(assigned_to_user_id);
CREATE INDEX tickets_last_modified_by_user_id_idx ON tickets(last_modified_by_user_id);
CREATE INDEX tickets_state_id_idx ON tickets(state_id);
CREATE INDEX tickets_severity_id_idx ON tickets(severity_id);
