CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  author_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL,
  modified_at TIMESTAMPTZ NOT NULL,
  message TEXT NOT NULL,
  related_comment_id BIGINT REFERENCES comments(id) ON DELETE SET NULL
);

CREATE INDEX comments_ticket_id_idx ON comments(ticket_id);
CREATE INDEX comments_author_user_id_idx ON comments(author_user_id);
CREATE INDEX comments_related_comment_id_idx ON comments(related_comment_id);
