CREATE TABLE time_tracking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE RESTRICT,
  duration_minutes INTEGER NOT NULL,
  logged_at TIMESTAMPTZ NOT NULL,
  description TEXT,
  CONSTRAINT time_tracking_duration_minutes_check CHECK (duration_minutes > 0)
);

CREATE INDEX time_tracking_ticket_id_idx ON time_tracking(ticket_id);
CREATE INDEX time_tracking_user_id_idx ON time_tracking(user_id);
CREATE INDEX time_tracking_activity_id_idx ON time_tracking(activity_id);
CREATE INDEX time_tracking_logged_at_idx ON time_tracking(logged_at);
