CREATE TABLE permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  area VARCHAR(50) NOT NULL,
  can_read BOOLEAN NOT NULL DEFAULT FALSE,
  can_create BOOLEAN NOT NULL DEFAULT FALSE,
  can_modify BOOLEAN NOT NULL DEFAULT FALSE,
  can_delete BOOLEAN NOT NULL DEFAULT FALSE,
  can_reassign BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT permissions_area_check CHECK (area IN ('dashboard', 'ticket', 'comment')),
  CONSTRAINT permissions_role_area_unique UNIQUE (role_id, area)
);

CREATE INDEX permissions_role_id_idx ON permissions(role_id);
