package io.github.oleksiybondar.api.domain.auth

import io.github.oleksiybondar.api.domain.user.UserId

import java.time.Instant
import java.util.UUID

/** Stable identifier of an authentication session stored on the backend. */
final case class SessionId(value: UUID) extends AnyVal

/** Opaque access token returned to clients for authenticated API calls. */
final case class AccessToken(value: String) extends AnyVal

/** Opaque refresh token used to rotate sessions without re-entering credentials. */
final case class RefreshToken(value: UUID) extends AnyVal

/** Persisted authentication session tracked for refresh, logout, and revocation. */
final case class AuthSession(
    /** Unique session identifier generated by the backend. */
    id: SessionId,
    /** User that owns the session. */
    userId: UserId,
    /** Refresh token currently assigned to the session. */
    refreshToken: RefreshToken,
    /** Timestamp when the session was created. */
    createdAt: Instant,
    /** Revocation time when the session has been explicitly invalidated. */
    revokedAt: Option[Instant],
    /** Absolute time after which the session can no longer be refreshed. */
    expiresAt: Instant
)

/** Claims encoded into issued access tokens. */
final case class AccessTokenClaims(
    /** Authenticated user carried by the token. */
    userId: UserId,
    /** Session associated with the token. */
    sessionId: SessionId,
    /** Unique token identifier for traceability and future revocation strategies. */
    tokenId: UUID,
    /** Token issuance timestamp. */
    issuedAt: Instant,
    /** Token expiry timestamp. */
    expiresAt: Instant
)

/** Pair of tokens returned after successful authentication-related operations. */
final case class AuthTokens(
    /** Short-lived bearer token used for authenticated requests. */
    accessToken: AccessToken,
    /** Long-lived token used to rotate the access token. */
    refreshToken: RefreshToken,
    /** Token scheme expected by clients, usually `Bearer`. */
    tokenType: String,
    /** Access token lifetime in seconds. */
    expiresIn: Long
)
