rules = [
  OrganizeImports,
  ExplicitResultTypes,
  DisableSyntax,
  RedundantSyntax
]

OrganizeImports {
  groupedImports = Merge
  removeUnused = false
}

ExplicitResultTypes.memberKind = [
  Def,
  Val
]
ExplicitResultTypes.memberVisibility = [
  Public,
  Protected
]
ExplicitResultTypes.skipSimpleDefinitions = []
ExplicitResultTypes.fatalWarnings = true

DisableSyntax.noVars = true
DisableSyntax.noThrows = true
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
